import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/models.dart';

/// ──────────────────────────────────────────────────────────────
/// DATABASE SERVICE — Supabase Migration
/// ──────────────────────────────────────────────────────────────

final databaseServiceProvider =
    Provider<DatabaseService>((ref) => DatabaseService());

class DatabaseService {
  final SupabaseClient _db = Supabase.instance.client;

  // ─── DOCTORS ───

  Future<List<DoctorModel>> getDoctors({
    String? specialty,
    String? searchQuery,
    String sortBy = 'rating',
  }) async {
    var query = _db.from('doctors').select().eq('is_active', true);

    if (specialty != null && specialty.isNotEmpty) {
      query = query.eq('specialty', specialty);
    }

    final response = await query;
    var doctors = response
        .map((doc) => DoctorModel.fromJson(doc))
        .toList();

    if (searchQuery != null && searchQuery.isNotEmpty) {
      final q = searchQuery.toLowerCase();
      doctors = doctors
          .where((d) =>
              d.name.toLowerCase().contains(q) ||
              d.specialty.toLowerCase().contains(q))
          .toList();
    }

    switch (sortBy) {
      case 'rating':
        doctors.sort((a, b) => b.rating.compareTo(a.rating));
        break;
      case 'experience':
        doctors.sort((a, b) => b.experienceYears.compareTo(a.experienceYears));
        break;
      case 'fee_low':
        doctors.sort((a, b) => a.consultationFee.compareTo(b.consultationFee));
        break;
      case 'fee_high':
        doctors.sort((a, b) => b.consultationFee.compareTo(a.consultationFee));
        break;
    }

    return doctors;
  }

  Future<DoctorModel?> getDoctor(String doctorId) async {
    final response = await _db.from('doctors').select().eq('id', doctorId).maybeSingle();
    if (response != null) {
      return DoctorModel.fromJson(response);
    }
    return null;
  }

  Future<void> addDoctor(DoctorModel doctor) async {
    await _db.from('doctors').insert(doctor.toJson());
  }

  Future<void> updateDoctor(DoctorModel doctor) async {
    await _db.from('doctors').update(doctor.toJson()).eq('id', doctor.id);
  }

  Future<void> deleteDoctor(String doctorId) async {
    await _db.from('doctors').update({'is_active': false}).eq('id', doctorId);
  }

  // ─── APPOINTMENTS ───

  Future<List<AppointmentModel>> getAppointments({
    String? patientId,
    String? doctorId,
    AppointmentStatus? status,
  }) async {
    var query = _db.from('appointments').select();

    if (patientId != null) {
      query = query.eq('patientId', patientId);
    }
    if (doctorId != null) {
      query = query.eq('doctorId', doctorId);
    }
    if (status != null) {
      query = query.eq('status', status.name);
    }

    final response = await query;
    var list = response
        .map((doc) => AppointmentModel.fromJson(doc))
        .toList();

    list.sort((a, b) => b.date.compareTo(a.date));
    return list;
  }

  Future<List<AppointmentModel>> getAllAppointments() async {
    final response = await _db.from('appointments').select();
    var list = response
        .map((doc) => AppointmentModel.fromJson(doc))
        .toList();
    list.sort((a, b) => b.date.compareTo(a.date));
    return list;
  }

  Future<AppointmentModel> createAppointment(AppointmentModel appointment) async {
    // Generate UUID if empty
    final idToSave = appointment.id.isEmpty ? _db.auth.currentUser!.id : appointment.id; // Just as a fallback
    // Usually UUID is generated by the database if not provided, but we can rely on Supabase returning the inserted row.
    final response = await _db.from('appointments').insert(appointment.toJson()).select().single();
    return AppointmentModel.fromJson(response);
  }

  Future<void> updateAppointmentStatus(
      String appointmentId, AppointmentStatus status) async {
    await _db.from('appointments').update({
      'status': status.name,
      'updatedAt': DateTime.now().toIso8601String(),
    }).eq('id', appointmentId);
  }

  // ─── PATIENTS ───

  Future<List<PatientModel>> getAllPatients() async {
    final response = await _db.from('users').select().eq('role', 'patient');
    return response.map((doc) {
      return PatientModel(
        uid: doc['uid'],
        age: 0,
        gender: 'Not specified',
        bloodGroup: 'Not specified',
      );
    }).toList();
  }

  Future<void> savePatientProfile(PatientModel patient) async {
    await _db.from('patient_profiles').upsert({
      'uid': patient.uid,
      'age': patient.age,
      'gender': patient.gender,
      'bloodGroup': patient.bloodGroup,
    });
  }

  // ─── HEALTH TIPS ───

  Future<List<HealthTipModel>> getHealthTips() async {
    final response = await _db.from('health_tips').select();
    return response
        .map((doc) => HealthTipModel.fromJson(doc))
        .toList();
  }

  Future<void> addHealthTip(HealthTipModel tip) async {
    await _db.from('health_tips').insert(tip.toJson());
  }

  // ─── SPECIALTIES ───

  List<String> getSpecialties() {
    return [
      'General Physician',
      'Cardiologist',
      'Dermatologist',
      'Orthopedic',
      'Pediatrician',
      'Neurologist',
      'Gynecologist',
      'ENT Specialist',
      'Ophthalmologist',
      'Psychiatrist',
      'Dentist',
      'Urologist',
    ];
  }
}
